### ISSUE TITLE
Seemingly irrelevant sentence in the Introducing Form Helpers section

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood-tutorial#10]
[This section](https://learn.redwoodjs.com/docs/tutorial/everyones-favorite-thing-to-build-forms/#introducing-form-helpers)

![image](https://user-images.githubusercontent.com/2712405/112735429-3d988d80-8f22-11eb-8cf8-0adc0227f55f.png)

**Comment by cannikin** [comment]
Color commentary. Although I don't remember adding the `...wait for it...` part... that doesn't seem like my voice. But it's just a quippy introduction to the tag.

**Comment by adriatic** [comment]
I like the humor present in the tutorial, so with your explanation, I think this comment is just fine 😄
