### ISSUE TITLE
Update src/lib/auth.js to current release candidate template

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood-tutorial#31]
The template has changed to do a couple more checks, we need to update to the latest here: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template

**Comment by jtoar** [comment]
@cannikin looks like you fixed this one in a commit; I'll close for now but reopen if that's not the case.
