### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by jiftuq** [redwoodjs/redwood-tutorial#4]
When i run yarn rw test it fails and i can't create storybooks, it give this error:

api/src/services/posts/posts.test.js (43.42 s)
  ● posts › returns a list of posts

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 
5000 ms timeout specified by jest.setTimeout.Error:

      2 | 
      3 | describe('posts', () => {
    > 4 |   scenario('returns a list of posts', async (scenario) => {
        |   ^
      5 |     const list = await posts()
      6 | 
      7 |     expect(list.length).toEqual(Object.keys(scenario.post).length)

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at scenario (../node_modules/@redwoodjs/core/dist/configs/node/jest.setup.js:106:17)
      at Suite.<anonymous> (src/services/posts/posts.test.js:4:3)
      at Object.<anonymous> (src/services/posts/posts.test.js:3:1)

  ● posts › returns a single post by ID

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: 2

       5 |     const list = await posts()
       6 | 
    >  7 |     expect(list.length).toEqual(Object.keys(scenario.post).length)
         |                         ^
       8 |     expect(list[0].title).toEqual(scenario.post.first.title)
       9 |   })
      10 | 

      at src/services/posts/posts.test.js:7:25
      at Object.<anonymous> (../node_modules/@redwoodjs/core/dist/configs/node/jest.setup.js:133:16)

**Comment by cannikin** [comment]
Is this after just checking out the existing codebase and running the tests, or did you make any changes anywhere?

**Comment by cannikin** [comment]
Just updated the code for v1.0 and tests are running 100% pass.
