### ISSUE TITLE
Bad link in the README.md

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood-tutorial#44]
Paragraph after https://github.com/redwoodjs/redwood-tutorial#setup

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2712405/165396343-980ca22d-ba30-456a-b9dd-75f5b373b0b7.png">

This link is https://redwoodjs.com/tutorial2/prerequisites
Should be. https://redwoodjs.com/tutorial/prerequisites

Not having a "proved RW contributor" title, I believe that reporting the problem this way might be easier to process than via a PR.

**Comment by thedavidprice** [comment]
Great catch! Fixed here https://github.com/redwoodjs/redwood-tutorial/commit/bc83d35ac7f4d5f437acb79dbe8bda5596412bd5
