### ISSUE TITLE
Prisma Studio in Tutorial Chapter 2 are planning to stop support

### ISSUE THREAD

**Issue by WoodRex** [redwoodjs/redwood-tutorial#54]
https://www.prisma.io/studio which will get updated later to remove the download links to the Electron app and switch to the CLI usage.

**Comment by WoodRex** [comment]
https://github.com/prisma/studio/issues/845

**Comment by jtoar** [comment]
@WoodRex thanks for the heads up. I'm pretty sure that we only call out to the CLI version in the tutorial, which prisma plans to maintain, so we should be ok.

**Comment by WoodRex** [comment]
Great!
