### ISSUE TITLE
use shorter method definition syntax?

### ISSUE THREAD

**Issue by benatkin** [redwoodjs/redwood-tutorial#6]
How about using the [ES2015 method definition syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#syntax)? If it was a class component, the `=>` would be needed, but since it isn't and there's no use of `this`, it is slightly shorter.

A very minor suggestion, but since this code is going to be copied and pasted a lot, it might be nice if it is actually an improvement.

```js
  const [updatePost, { loading, error }] = useMutation(UPDATE_POST_MUTATION, {
    onCompleted() {
      navigate(routes.posts())
      addMessage('Post updated.', { classes: 'rw-flash-success' })
    },
  })
```

instead of:

```js
const [updatePost, { loading, error }] = useMutation(UPDATE_POST_MUTATION, {
    onCompleted: () => {
      navigate(routes.posts())
      addMessage('Post updated.', { classes: 'rw-flash-success' })
    },
  })
```

on https://github.com/redwoodjs/redwood-tutorial/blob/main/web/src/components/EditPostCell/EditPostCell.js

**Comment by cannikin** [comment]
Yeah, I'm just not sure if people are used to seeing that syntax? I hardly ever see that in the wild, although I admit I don't go around inspecting tons of other people's projects very often.

**Comment by benatkin** [comment]
I see both often.

It would be nice if this could be outsourced to prettier, but it gladly accepts both =)

Maybe eslint has weighed in...

**Comment by benatkin** [comment]
eslint also accepts both, even when this isn't used, with the first rule I found https://eslint.org/docs/rules/object-shorthand

**Comment by benatkin** [comment]
I asked on their Discord.

Thanks. =)

**Comment by cannikin** [comment]
@peterp What do you think about this syntax? I feel like we don't use it in Redwood proper?

**Comment by ajcwebdev** [comment]
I tend to see people go with the arrow syntax whenever possible, but I think that's more about people being comfortable with it and knowing what to expect, so they just default to using it.

And this code comes out of the scaffold command, right? I wonder how many people even look at this code in the first place.

**Comment by cannikin** [comment]
We're going to stick with => for now, thanks!
